### Get Knowledge
GET {{HostAddress}}/knowledge

### Get Random Knowledge
GET {{HostAddress}}/knowledge/random

### Get Knowledge By Id
GET {{HostAddress}}/knowledge/114e433e-f36b-1410-8682-000a6a85c942