### Get Media Albums
GET {{HostAddress}}/media-albums

### Get Media Album By Id
GET {{HostAddress}}/media-albums/4b4e433e-f36b-1410-8682-000a6a85c942

### Get Media Album By Name
GET {{HostAddress}}/media-albums/test-media-album-1