// <auto-generated />
using System;
using MaaldoCom.Services.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaaldoCom.Services.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MaaldoComDbContext))]
    [Migration("20251230015254_InitSeed")]
    partial class InitSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Knowledge", (string)null);
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(7);

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(9);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<Guid>("MediaAlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("MediaAlbumId");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.MediaAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(6);

                    b.Property<string>("UrlFriendlyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UrlFriendlyName")
                        .IsUnique();

                    b.ToTable("MediaAlbums", (string)null);
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.MediaAlbumTag", b =>
                {
                    b.Property<Guid>("MediaAlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaAlbumId", "TagId");

                    b.ToTable("MediaAlbumTags", (string)null);
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.MediaTag", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaId", "TagId");

                    b.ToTable("MediaTags", (string)null);
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.Media", b =>
                {
                    b.HasOne("MaaldoCom.Services.Domain.Entities.MediaAlbum", "MediaAlbum")
                        .WithMany("Media")
                        .HasForeignKey("MediaAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAlbum");
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.MediaAlbumTag", b =>
                {
                    b.HasOne("MaaldoCom.Services.Domain.Entities.MediaAlbum", "MediaAlbum")
                        .WithMany("Tags")
                        .HasForeignKey("MediaAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaaldoCom.Services.Domain.Entities.Tag", "Tag")
                        .WithMany("MediaAlbumTags")
                        .HasForeignKey("MediaAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAlbum");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.MediaTag", b =>
                {
                    b.HasOne("MaaldoCom.Services.Domain.Entities.Media", "Media")
                        .WithMany("Tags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaaldoCom.Services.Domain.Entities.Tag", "Tag")
                        .WithMany("MediaTags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.Media", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.MediaAlbum", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MaaldoCom.Services.Domain.Entities.Tag", b =>
                {
                    b.Navigation("MediaAlbumTags");

                    b.Navigation("MediaTags");
                });
#pragma warning restore 612, 618
        }
    }
}
