INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('BRUTAL HONESTY','Actually there are dumb ideas.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('STAMINA','You''re so far behind now you may as well stop trying.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('REALISM','It really does matter whether you win or lose.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('REALITY','Winning isn''t everything, but it sure is better than losing.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('INTELLIGENCE','People tend to hold overly favorable views of their abilities  in many social and intellectual domains.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('CONSULTING','If you''re not part of the solution,  there''s good money to be made in prolonging the problem.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('ELITISM','It''s lonely at the top.  But it''s comforting to look down upon everyone at the bottom.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEMOTIVATION','Sometimes the best solution to morale problems  is just to fire all of the unhappy people.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('LONLINESS','If you find yourself struggling with lonliness,  you''re not alone.  And yet you are alone.  So Very Alone.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('ARROGANCE','The best leaders inspire by example.  When that''s not an option,  brute intimidation works pretty well too.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('CLUELESSNESS','There are no stupid questions,  but there are a lot of inquisitive idiots.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('INCOMPENTENCE','When you earnestly believe you can compensate  for a lack of skill by doubling your efforts,  theres no end to what you can''t do.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('IGNORANCE','It''s amazing how much easier it is for a team to work together when no one has any idea where they''re going.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('PRETENSION','The down side to being better than everyone else is   that people tend to assume your''re pretentious.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DYSFUNCTION','The only consistent feature of all of your dissatisfying relationships is you.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('IDIOCY','Never underestimate the power of stupid people in large groups.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('LAZINESS','Success is not a journey,  and not a destination.  So stop running.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('UNDERACHIEVEMENT','The tallest blade of grass is the first to be cut by the lawnmower.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('BURNOUT','Attitudes are contagious  Mine might kill you.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DOUBT','In the battle between you and the world,  bet on the world.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('PROCRASTINATION','Hard work often pays off after time,  but laziness always pays off now.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('MEDIOCRITY','It takes a lot less time   and most people wont notice the difference until its too late.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('MISTAKES','It could be that the purpose of your life   is only to serve as a warning to others.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('INEPTITUDE','If you cant learn to do something well,  learn to enjoy doing it poorly.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('FEAR','Until you have the courage to lose sight of the shore,  you will not know the terror of being forever lost at sea.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('HAZARDS','There is an island of opportunity in the middle  of every difficulty, miss that, though,  and youre pretty much doomed.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('IRRESPONSIBILITY','No single raindrop believes it is to blame for the flood.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('OVERCONFIDENCE','Before you attempt to beat the odds,  be sure you can survive the odds beating you.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('REGRET','It hurts to admit when you''ve made mistakes,  but when theyre big enough, the pain only last a second.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('RISKS','If you never try anything new,  you''ll miss out on many of lifes great disappointments.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('SACRIFICE','Your role may be thankless,   but if you''re willing to give it your all,  you just might bring success to those who outlast you.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('BITTERNESS','Never be afraid to share your dreams with the world,  because theres nothing the world loves more  than eating really sweet dreams.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('BLAME','The secret to success is knowing who to blame for your failures.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DARE TO SLACK','When birds fly in the proper formation,  they only need to exert half the effort.  Even in nature, teamwork results in collective laziness.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DELUSIONS','There is no joy greater than soaring high on the wings  of your dreams, except maybe the joy of watching a dreamer  who has nowhere to land but in the ocean of reality.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DISLOYALTY','There comes a time when every team must learn to sacrifice individuals.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DISSERVICE','It takes months to find a customer, but only seconds to lose one.  The good news is we should run out of them in no time.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('INSANITY','Its difficult to comprehend how insane some people can be,   especially when youre insane.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('ADVERSITY','That which does not kill me only postpones the inevitable.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('CONFORMITY','When people are free to do as they please,   they usually imitate each other.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DESPAIR','It''s always darkest just before it goes pitch black.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('HUMILIATION','The harder you try, the dumber you look.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('MISFORTUNE','While good fortune often eludes you,   Misfortune never misses.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('PROBLEMS','No matter how great and destructive your problems  may seem now, remember,  you''ve probably only seen the tip of them.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('TROUBLE','Luck cant last a lifetime, unless you die young.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('AGONY','Not all pain is gain.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEFEAT','For every winner, there are dozens of losers.    Odds are youre one of them.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('FAILURE','When your best just isn''t good enough.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('FUTILITY','You''ll always miss 100% of the shots you don''t take, and,   statistically speaking, 99% of the shots that you do.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('LOSING','If at first you dont succeed, failure may be your style.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('PESSIMISM','Every dark cloud has a silver lining,   but lightning kills hundreds of people  each year who are trying to find it.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('STUPIDITY','Quitters never win, Winners never quit,  but those that never win AND never quit are idiots.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEEP THOUGHTS','I''ve learned that you should''nt compare yourself to others,  they are more screwed up than you think.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEEP THOUGHTS','I''ve learned that you cannot make someone love you.  All you can do is stalk them and   hope they panic and give in.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEEP THOUGHTS','I''ve learned that you can keep puking   long after you think youre finished.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEEP THOUGHTS','I''ve learned that we are responsible for what we do,  unless we are celebrities.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEEP THOUGHTS','I''ve learned that regardless of how hot and steamy   a relationship is at first, the passion fades,   and there had better be a lot of money to take it''s place.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DEEP THOUGHTS','I''ve learned that the people you care most about in life   are taken from you too soon and all the less important  ones just never go away.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('ALL ABOUT ME','When I grow up I want to be just like me.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('ALL ABOUT ME','I love not being You.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('DISAPPROVAL','The more you disapprove, the more fun it is for me')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('FLATTERY','If you want to get to the top,  Be prepared to kiss a lot of the bottom.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('GET TO WORK','You aren''t being paid to believe  in the power of your dreams.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('GOALS','It''s to avoid standing directly between  a Competitive Jerk and their Goals')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('INDIFFERENCE','It takes 43 muscles to frown and 17 to smile,  but it doesn''t take any to just sit there  with a dumb look on your face.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('INDIVIDUALITY','Always remember that you are unique.  Just Like Everybody Else.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('LEADERS','Leaders are Like Eagles.  We dont Have Either of Them Here.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('LIMITATIONS','Until you spread your wings,  Youll have no idea how far you can walk.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('MEETINGS','None of us is as Dumb as all of us together.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('MOTIVATION','If a Pretty Poster and a Cute Saying are all  It takes to motivate you, you probably have a  very easy job.  The Kind Robots will do soon.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('PLANNING','Much work remains to be done before we can  Announce our total failure to make any progress.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('STRIFE','As long as we have each other,   We''ll never run out of problems.')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('COMPUTER LOVE','Hey You''re Kind of Cute.  Ever Consider a Relationship with a Computer?')
INSERT INTO [KNOWLEDGE] ([Title],[Quote])VALUES('FRIENDSHIP','A good friend will come and bail you out of jail  but a true friend will be sitting next to you saying: Gosh, that was fun.')